// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Scanner.flex

/* JFlex Scanner Specification */

import java.io.*;
import java.util.*;


@SuppressWarnings("fallthrough")
public class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\1\22\0\1\1\1\4"+
    "\1\5\1\6\1\0\1\7\1\10\1\11\2\12\1\13"+
    "\1\14\1\12\1\15\1\16\1\17\12\20\2\12\1\21"+
    "\1\22\1\21\2\0\4\23\1\24\25\23\1\12\1\25"+
    "\1\12\1\0\1\26\1\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\26\1\35\1\36\1\26\1\37\1\40"+
    "\1\26\1\41\1\42\1\43\1\26\1\44\1\45\1\46"+
    "\1\47\5\26\1\12\1\50\1\12\7\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\2\1"+
    "\1\6\4\5\1\7\1\10\1\11\1\12\14\1\1\10"+
    "\1\13\1\0\1\14\1\15\1\3\1\16\1\0\1\11"+
    "\1\17\1\20\1\0\1\12\16\0\1\21\1\22\1\12"+
    "\14\0\1\14\1\22\1\0\1\12\4\0\1\23\4\0"+
    "\1\24\1\22\1\0\1\22\1\12\5\0\1\22\1\12"+
    "\2\0\1\22\1\12\1\22\1\12\1\0\1\12\1\25"+
    "\1\12\1\0\1\12\1\0\1\25\24\12\1\0\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\51\0\122\0\173\0\244\0\51\0\315"+
    "\0\366\0\51\0\u011f\0\u0148\0\u0171\0\u019a\0\u01c3\0\122"+
    "\0\122\0\u01ec\0\u0215\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2"+
    "\0\u030b\0\u0334\0\u035d\0\u0386\0\u03af\0\u03d8\0\51\0\51"+
    "\0\u0401\0\u042a\0\u0453\0\51\0\u047c\0\u04a5\0\51\0\51"+
    "\0\51\0\u04ce\0\u04f7\0\u0520\0\u0549\0\u0572\0\u059b\0\u05c4"+
    "\0\u05ed\0\u0616\0\u063f\0\u0668\0\u0691\0\u06ba\0\u06e3\0\u070c"+
    "\0\u0735\0\51\0\u075e\0\u0787\0\u07b0\0\u07d9\0\u0802\0\u082b"+
    "\0\u0854\0\u087d\0\u08a6\0\u08cf\0\u08f8\0\u0921\0\u094a\0\u0973"+
    "\0\51\0\u099c\0\u09c5\0\u09ee\0\u0a17\0\u0a40\0\u0a69\0\u0a92"+
    "\0\51\0\u0abb\0\u0ae4\0\u0b0d\0\u0b36\0\51\0\u0b5f\0\u0b88"+
    "\0\u0b88\0\u0bb1\0\u0bda\0\u0c03\0\u0c2c\0\u0c55\0\u0c7e\0\u0ca7"+
    "\0\u0cd0\0\u0cf9\0\u0d22\0\u0d4b\0\u0d74\0\u0d9d\0\u0dc6\0\u0def"+
    "\0\u0e18\0\u0e41\0\u0e6a\0\u0e93\0\u0ebc\0\u0ee5\0\u0ee5\0\u0f0e"+
    "\0\u0f37\0\u0f60\0\u0f89\0\u0fb2\0\u0fdb\0\u1004\0\u102d\0\u1056"+
    "\0\u107f\0\u10a8\0\u10d1\0\u10fa\0\u1123\0\u114c\0\u1175\0\u119e"+
    "\0\u11c7\0\u11f0\0\u1219\0\u1242\0\u1242";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\2\1\16\1\17"+
    "\1\20\1\21\2\22\3\2\1\23\1\24\1\25\1\26"+
    "\1\27\1\2\1\30\1\2\1\31\1\2\1\32\1\2"+
    "\1\33\1\34\1\35\1\2\1\36\73\0\1\37\26\0"+
    "\2\5\1\0\2\5\1\40\17\5\1\41\23\5\6\0"+
    "\1\42\4\0\1\43\45\0\1\44\40\0\2\45\1\0"+
    "\6\45\1\0\13\45\1\46\23\45\13\0\1\7\6\0"+
    "\1\47\42\0\1\50\3\0\1\17\1\0\1\47\43\0"+
    "\1\51\2\0\1\17\1\0\1\47\50\0\1\47\44\0"+
    "\1\52\1\0\1\17\50\0\1\53\5\0\22\53\45\0"+
    "\1\54\46\0\1\55\41\0\1\56\55\0\1\57\37\0"+
    "\1\60\6\0\1\61\10\0\1\62\42\0\1\63\51\0"+
    "\1\64\55\0\1\65\34\0\1\66\63\0\1\67\46\0"+
    "\1\70\54\0\1\44\2\0\1\5\2\0\1\5\17\0"+
    "\1\5\16\0\1\5\1\0\1\5\2\0\2\42\1\0"+
    "\46\42\13\43\1\71\35\43\11\0\1\72\41\0\1\45"+
    "\6\0\1\45\13\0\1\45\16\0\1\45\1\0\1\45"+
    "\22\0\1\73\50\0\1\74\5\0\22\74\34\0\1\75"+
    "\56\0\1\76\40\0\1\77\64\0\1\100\43\0\1\101"+
    "\51\0\1\102\50\0\1\103\52\0\1\104\47\0\1\105"+
    "\54\0\1\63\50\0\1\106\31\0\1\107\70\0\1\110"+
    "\1\0\6\43\1\111\4\43\1\71\35\43\20\0\1\112"+
    "\3\0\1\113\6\0\1\113\35\0\1\114\5\0\22\114"+
    "\30\0\1\115\53\0\1\116\13\0\1\117\42\0\1\120"+
    "\43\0\1\121\62\0\1\110\41\0\1\122\43\0\1\123"+
    "\66\0\1\124\44\0\1\121\54\0\1\125\45\0\1\124"+
    "\37\0\1\126\35\0\1\127\3\0\1\113\6\0\1\113"+
    "\31\0\2\130\2\0\1\131\50\0\1\132\5\0\22\132"+
    "\40\0\1\121\47\0\1\123\50\0\1\133\41\0\1\134"+
    "\66\0\1\135\51\0\1\136\50\0\1\121\46\0\1\137"+
    "\24\0\1\140\3\0\1\113\6\0\1\113\35\0\1\131"+
    "\50\0\1\141\5\0\22\141\42\0\1\142\53\0\1\100"+
    "\41\0\1\121\51\0\1\143\53\0\1\121\27\0\1\144"+
    "\3\0\1\113\6\0\1\113\35\0\1\145\5\0\22\145"+
    "\50\0\1\100\43\0\1\137\26\0\1\146\3\0\1\113"+
    "\6\0\1\113\35\0\1\147\5\0\22\147\21\0\1\150"+
    "\3\0\1\113\6\0\1\113\35\0\1\151\5\0\22\151"+
    "\21\0\1\152\50\0\1\153\5\0\22\153\21\0\1\152"+
    "\3\0\1\154\6\0\1\154\35\0\1\155\5\0\22\155"+
    "\15\0\2\156\2\0\1\157\50\0\1\160\5\0\22\160"+
    "\21\0\1\157\50\0\1\161\5\0\22\161\21\0\1\162"+
    "\5\0\22\162\21\0\1\163\5\0\22\163\21\0\1\164"+
    "\5\0\22\164\21\0\1\165\5\0\22\165\21\0\1\166"+
    "\5\0\22\166\21\0\1\167\5\0\22\167\21\0\1\170"+
    "\5\0\22\170\21\0\1\171\5\0\22\171\21\0\1\172"+
    "\5\0\22\172\21\0\1\173\5\0\22\173\21\0\1\174"+
    "\5\0\22\174\21\0\1\175\5\0\22\175\21\0\1\176"+
    "\5\0\22\176\21\0\1\177\5\0\22\177\21\0\1\200"+
    "\5\0\22\200\21\0\1\201\5\0\22\201\21\0\1\202"+
    "\5\0\22\202\21\0\1\203\5\0\22\203\21\0\1\204"+
    "\5\0\22\204\21\0\1\205\5\0\22\205\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4715];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\2\1\1\11\24\1\2\11"+
    "\1\0\2\1\1\11\1\1\1\0\3\11\1\0\1\1"+
    "\16\0\1\11\2\1\14\0\1\11\1\1\1\0\1\1"+
    "\4\0\1\11\4\0\1\11\1\1\1\0\2\1\5\0"+
    "\2\1\2\0\4\1\1\0\3\1\1\0\1\1\1\0"+
    "\25\1\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private List<Token> tokens = new ArrayList<>();
    private ErrorHandler errorHandler = new ErrorHandler();
    private SymbolTable symbolTable = new SymbolTable();
    private Map<TokenType, Integer> tokenCounts = new HashMap<>();
    private int commentCount = 0;

    private void addToken(TokenType type, String lexeme) {
        Token token = new Token(type, lexeme, yyline + 1, yycolumn + 1);
        tokens.add(token);
        tokenCounts.put(type, tokenCounts.getOrDefault(type, 0) + 1);
        
        if (type == TokenType.IDENTIFIER) {
            symbolTable.addIdentifier(lexeme, yyline + 1, yycolumn + 1);
        }
    }

    public List<Token> getTokens() {
        return tokens;
    }

    public ErrorHandler getErrorHandler() {
        return errorHandler;
    }

    public SymbolTable getSymbolTable() {
        return symbolTable;
    }

    public void printTokens() {
        System.out.println("\n=== Tokens (JFlex) ===");
        for (Token token : tokens) {
            System.out.println(token);
        }
    }

    public void printStatistics() {
        System.out.println("\n=== Statistics (JFlex) ===");
        System.out.println("Total tokens: " + tokens.size());
        System.out.println("Lines processed: " + (yyline + 1));
        System.out.println("Comments removed: " + commentCount);
        System.out.println("\nToken counts by type:");
        
        tokenCounts.entrySet().stream()
            .sorted(Map.Entry.<TokenType, Integer>comparingByValue().reversed())
            .forEach(entry -> 
                System.out.println("  " + entry.getKey() + ": " + entry.getValue()));
    }

    public static void main(String[] args) {
        if (args.length == 0) {
            System.out.println("Usage: java Yylex <input-file>");
            return;
        }

        try {
            Yylex scanner = new Yylex(new FileReader(args[0]));
            scanner.yylex();
            
            scanner.printTokens();
            scanner.printStatistics();
            scanner.getSymbolTable().print();
            scanner.getErrorHandler().printErrorSummary();
            
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public void yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     return;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errorHandler.reportInvalidCharacter(yyline + 1, yycolumn + 1, yytext().charAt(0));
            }
          // fall through
          case 23: break;
          case 2:
            { /* skip */
            }
          // fall through
          case 24: break;
          case 3:
            { addToken(TokenType.LOGICAL_OP, yytext());
            }
          // fall through
          case 25: break;
          case 4:
            { errorHandler.reportUnterminatedString(yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 26: break;
          case 5:
            { addToken(TokenType.ARITHMETIC_OP, yytext());
            }
          // fall through
          case 27: break;
          case 6:
            { addToken(TokenType.PUNCTUATOR, yytext());
            }
          // fall through
          case 28: break;
          case 7:
            { addToken(TokenType.INTEGER_LITERAL, yytext());
            }
          // fall through
          case 29: break;
          case 8:
            { addToken(TokenType.RELATIONAL_OP, yytext());
            }
          // fall through
          case 30: break;
          case 9:
            { addToken(TokenType.ASSIGNMENT_OP, yytext());
            }
          // fall through
          case 31: break;
          case 10:
            { addToken(TokenType.IDENTIFIER, yytext());
            }
          // fall through
          case 32: break;
          case 11:
            { addToken(TokenType.STRING_LITERAL, yytext());
            }
          // fall through
          case 33: break;
          case 12:
            { commentCount++;
            }
          // fall through
          case 34: break;
          case 13:
            { errorHandler.reportUnclosedComment(yyline + 1, yycolumn + 1);
            }
          // fall through
          case 35: break;
          case 14:
            { errorHandler.reportUnterminatedChar(yyline + 1, yycolumn + 1, yytext());
            }
          // fall through
          case 36: break;
          case 15:
            { addToken(TokenType.INCREMENT_OP, yytext());
            }
          // fall through
          case 37: break;
          case 16:
            { addToken(TokenType.DECREMENT_OP, yytext());
            }
          // fall through
          case 38: break;
          case 17:
            { addToken(TokenType.CHAR_LITERAL, yytext());
            }
          // fall through
          case 39: break;
          case 18:
            { addToken(TokenType.FLOAT_LITERAL, yytext());
            }
          // fall through
          case 40: break;
          case 19:
            { addToken(TokenType.KEYWORD, yytext());
            }
          // fall through
          case 41: break;
          case 20:
            { addToken(TokenType.BOOLEAN_LITERAL, yytext());
            }
          // fall through
          case 42: break;
          case 21:
            { errorHandler.reportMalformedLiteral(yyline + 1, yycolumn + 1, yytext(), 
                        "More than 6 decimal digits");
            }
          // fall through
          case 43: break;
          case 22:
            { errorHandler.reportInvalidIdentifier(yyline + 1, yycolumn + 1, yytext(), 
                        "Identifier exceeds 31 characters");
            }
          // fall through
          case 44: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
